//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class durgunka_1Entities : DbContext
    {
        public durgunka_1Entities()
            : base("name=durgunka_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<musteriler> musterilers { get; set; }
    
        public virtual int kisiEkle(string userad, string usersoyad, string usersehir, Nullable<long> usertc, Nullable<long> usertelefon)
        {
            var useradParameter = userad != null ?
                new ObjectParameter("userad", userad) :
                new ObjectParameter("userad", typeof(string));
    
            var usersoyadParameter = usersoyad != null ?
                new ObjectParameter("usersoyad", usersoyad) :
                new ObjectParameter("usersoyad", typeof(string));
    
            var usersehirParameter = usersehir != null ?
                new ObjectParameter("usersehir", usersehir) :
                new ObjectParameter("usersehir", typeof(string));
    
            var usertcParameter = usertc.HasValue ?
                new ObjectParameter("usertc", usertc) :
                new ObjectParameter("usertc", typeof(long));
    
            var usertelefonParameter = usertelefon.HasValue ?
                new ObjectParameter("usertelefon", usertelefon) :
                new ObjectParameter("usertelefon", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("kisiEkle", useradParameter, usersoyadParameter, usersehirParameter, usertcParameter, usertelefonParameter);
        }
    
        public virtual int kisiGuncelle(Nullable<int> userid, string userad, string usersoyad, string usersehir, Nullable<long> usertc, Nullable<long> usertelefon)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var useradParameter = userad != null ?
                new ObjectParameter("userad", userad) :
                new ObjectParameter("userad", typeof(string));
    
            var usersoyadParameter = usersoyad != null ?
                new ObjectParameter("usersoyad", usersoyad) :
                new ObjectParameter("usersoyad", typeof(string));
    
            var usersehirParameter = usersehir != null ?
                new ObjectParameter("usersehir", usersehir) :
                new ObjectParameter("usersehir", typeof(string));
    
            var usertcParameter = usertc.HasValue ?
                new ObjectParameter("usertc", usertc) :
                new ObjectParameter("usertc", typeof(long));
    
            var usertelefonParameter = usertelefon.HasValue ?
                new ObjectParameter("usertelefon", usertelefon) :
                new ObjectParameter("usertelefon", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("kisiGuncelle", useridParameter, useradParameter, usersoyadParameter, usersehirParameter, usertcParameter, usertelefonParameter);
        }
    
        public virtual int kisiSil(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("kisiSil", useridParameter);
        }
    }
}
