//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        public int musteriid { get; set; }
        public string musteriad { get; set; }
        public string musterisoyad { get; set; }
        public string musterisehir { get; set; }
        public long musteritc { get; set; }
        public long musteritelefon { get; set; }
    }
}
